# ArgoCD Root Application (App-of-Apps pattern)
# Applied from terraform.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allflex-apps
  source:
    repoURL: https://github.com/Garmonovm/doker_java_k8s_argo_cicd.git
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
