# ===========================================================================
# Java App — Development (watches develop branch)
# ArgoCD auto-syncs when CI updates the values file
# ===========================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-development
  namespace: argocd
  labels:
    app: java-app
    env: development
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: allflex-apps

  source:
    repoURL: https://github.com/Garmonovm/doker_java_k8s_argo_cicd.git
    targetRevision: develop
    path: helm/microservice
    helm:
      valueFiles:
        - ../values/java-app/development.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
